// Mocks generated by Mockito 5.4.4 from annotations
// in boofer/test/services/mesh_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;

import 'package:boofer/models/message_model.dart' as _i4;
import 'package:boofer/services/mesh_reception_handler.dart' as _i5;
import 'package:boofer/services/message_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMessageRepository extends _i1.Mock
    implements _i2.IMessageRepository {
  MockIMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Message>> get messagesStream => (super.noSuchMethod(
        Invocation.getter(#messagesStream),
        returnValue: _i3.Stream<List<_i4.Message>>.empty(),
      ) as _i3.Stream<List<_i4.Message>>);

  @override
  _i3.Future<List<_i4.Message>> getMessages({
    int? offset = 0,
    int? limit = 50,
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #offset: offset,
            #limit: limit,
            #ascending: ascending,
          },
        ),
        returnValue: _i3.Future<List<_i4.Message>>.value(<_i4.Message>[]),
      ) as _i3.Future<List<_i4.Message>>);

  @override
  _i3.Future<List<_i4.Message>> getMessagesByConversation(
          String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesByConversation,
          [conversationId],
        ),
        returnValue: _i3.Future<List<_i4.Message>>.value(<_i4.Message>[]),
      ) as _i3.Future<List<_i4.Message>>);

  @override
  _i3.Future<List<_i4.Message>> getMessagesByStatus(
          _i4.MessageStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesByStatus,
          [status],
        ),
        returnValue: _i3.Future<List<_i4.Message>>.value(<_i4.Message>[]),
      ) as _i3.Future<List<_i4.Message>>);

  @override
  _i3.Future<List<_i4.Message>> getOfflineMessages() => (super.noSuchMethod(
        Invocation.method(
          #getOfflineMessages,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Message>>.value(<_i4.Message>[]),
      ) as _i3.Future<List<_i4.Message>>);

  @override
  _i3.Future<int> saveMessage(_i4.Message? message) => (super.noSuchMethod(
        Invocation.method(
          #saveMessage,
          [message],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<int>> saveMessages(List<_i4.Message>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMessages,
          [messages],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<void> updateMessageStatus(
    int? messageId,
    _i4.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessageStatus,
          [
            messageId,
            status,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMessageStatuses(
    List<int>? messageIds,
    _i4.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessageStatuses,
          [
            messageIds,
            status,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> deleteMessage(int? messageId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [messageId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteOldMessages(DateTime? cutoffDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldMessages,
          [cutoffDate],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getMessageCount() => (super.noSuchMethod(
        Invocation.method(
          #getMessageCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getMessageCountByStatus(_i4.MessageStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageCountByStatus,
          [status],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> messageExists(String? messageHash) => (super.noSuchMethod(
        Invocation.method(
          #messageExists,
          [messageHash],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Message?> findMessageByHash(String? messageHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMessageByHash,
          [messageHash],
        ),
        returnValue: _i3.Future<_i4.Message?>.value(),
      ) as _i3.Future<_i4.Message?>);

  @override
  _i3.Future<void> clearAllMessages() => (super.noSuchMethod(
        Invocation.method(
          #clearAllMessages,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [MeshReceptionHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeshReceptionHandler extends _i1.Mock
    implements _i5.MeshReceptionHandler {
  MockMeshReceptionHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Message> get processedMessages => (super.noSuchMethod(
        Invocation.getter(#processedMessages),
        returnValue: _i3.Stream<_i4.Message>.empty(),
      ) as _i3.Stream<_i4.Message>);

  @override
  _i3.Stream<String> get errors => (super.noSuchMethod(
        Invocation.getter(#errors),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<void> processIncomingData(
    _i6.Uint8List? data,
    String? senderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processIncomingData,
          [
            data,
            senderId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> processBatchMessages(
    List<_i6.Uint8List>? dataList,
    List<String>? senderIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processBatchMessages,
          [
            dataList,
            senderIds,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool validateMessageIntegrity(_i4.Message? message) => (super.noSuchMethod(
        Invocation.method(
          #validateMessageIntegrity,
          [message],
        ),
        returnValue: false,
      ) as bool);
}
