// Mocks generated by Mockito 5.4.4 from annotations
// in boofer/test/services/message_queue_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:boofer/models/message_model.dart' as _i5;
import 'package:boofer/models/network_state.dart' as _i2;
import 'package:boofer/services/mesh_service.dart' as _i6;
import 'package:boofer/services/message_repository.dart' as _i3;
import 'package:boofer/services/network_service.dart' as _i8;
import 'package:boofer/services/online_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetworkState_0 extends _i1.SmartFake implements _i2.NetworkState {
  _FakeNetworkState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMessageRepository extends _i1.Mock
    implements _i3.IMessageRepository {
  MockIMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.Message>> get messagesStream => (super.noSuchMethod(
        Invocation.getter(#messagesStream),
        returnValue: _i4.Stream<List<_i5.Message>>.empty(),
      ) as _i4.Stream<List<_i5.Message>>);

  @override
  _i4.Future<List<_i5.Message>> getMessages({
    int? offset = 0,
    int? limit = 50,
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #offset: offset,
            #limit: limit,
            #ascending: ascending,
          },
        ),
        returnValue: _i4.Future<List<_i5.Message>>.value(<_i5.Message>[]),
      ) as _i4.Future<List<_i5.Message>>);

  @override
  _i4.Future<List<_i5.Message>> getMessagesByConversation(
          String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesByConversation,
          [conversationId],
        ),
        returnValue: _i4.Future<List<_i5.Message>>.value(<_i5.Message>[]),
      ) as _i4.Future<List<_i5.Message>>);

  @override
  _i4.Future<List<_i5.Message>> getMessagesByStatus(
          _i5.MessageStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessagesByStatus,
          [status],
        ),
        returnValue: _i4.Future<List<_i5.Message>>.value(<_i5.Message>[]),
      ) as _i4.Future<List<_i5.Message>>);

  @override
  _i4.Future<List<_i5.Message>> getOfflineMessages() => (super.noSuchMethod(
        Invocation.method(
          #getOfflineMessages,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Message>>.value(<_i5.Message>[]),
      ) as _i4.Future<List<_i5.Message>>);

  @override
  _i4.Future<int> saveMessage(_i5.Message? message) => (super.noSuchMethod(
        Invocation.method(
          #saveMessage,
          [message],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<int>> saveMessages(List<_i5.Message>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMessages,
          [messages],
        ),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  _i4.Future<void> updateMessageStatus(
    int? messageId,
    _i5.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessageStatus,
          [
            messageId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMessageStatuses(
    List<int>? messageIds,
    _i5.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMessageStatuses,
          [
            messageIds,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> deleteMessage(int? messageId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [messageId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> deleteOldMessages(DateTime? cutoffDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldMessages,
          [cutoffDate],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getMessageCount() => (super.noSuchMethod(
        Invocation.method(
          #getMessageCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getMessageCountByStatus(_i5.MessageStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessageCountByStatus,
          [status],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<bool> messageExists(String? messageHash) => (super.noSuchMethod(
        Invocation.method(
          #messageExists,
          [messageHash],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.Message?> findMessageByHash(String? messageHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMessageByHash,
          [messageHash],
        ),
        returnValue: _i4.Future<_i5.Message?>.value(),
      ) as _i4.Future<_i5.Message?>);

  @override
  _i4.Future<void> clearAllMessages() => (super.noSuchMethod(
        Invocation.method(
          #clearAllMessages,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IMeshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMeshService extends _i1.Mock implements _i6.IMeshService {
  MockIMeshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.Message> get incomingMessages => (super.noSuchMethod(
        Invocation.getter(#incomingMessages),
        returnValue: _i4.Stream<_i5.Message>.empty(),
      ) as _i4.Stream<_i5.Message>);

  @override
  _i4.Stream<int> get connectedPeersCount => (super.noSuchMethod(
        Invocation.getter(#connectedPeersCount),
        returnValue: _i4.Stream<int>.empty(),
      ) as _i4.Stream<int>);

  @override
  _i4.Stream<bool> get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isStarted => (super.noSuchMethod(
        Invocation.getter(#isStarted),
        returnValue: false,
      ) as bool);

  @override
  int get peersCount => (super.noSuchMethod(
        Invocation.getter(#peersCount),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> initialize(String? apiKey) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [apiKey],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendMeshMessage(
    String? text,
    String? senderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMeshMessage,
          [
            text,
            senderId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IOnlineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOnlineService extends _i1.Mock implements _i7.IOnlineService {
  MockIOnlineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.Message> get incomingMessages => (super.noSuchMethod(
        Invocation.getter(#incomingMessages),
        returnValue: _i4.Stream<_i5.Message>.empty(),
      ) as _i4.Stream<_i5.Message>);

  @override
  _i4.Stream<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize(
    String? supabaseUrl,
    String? supabaseAnonKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            supabaseUrl,
            supabaseAnonKey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendOnlineMessage(
    String? text,
    String? senderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOnlineMessage,
          [
            text,
            senderId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncOfflineMessages(List<_i5.Message>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncOfflineMessages,
          [messages],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [INetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkService extends _i1.Mock implements _i8.INetworkService {
  MockINetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.NetworkState> get networkState => (super.noSuchMethod(
        Invocation.getter(#networkState),
        returnValue: _i4.Stream<_i2.NetworkState>.empty(),
      ) as _i4.Stream<_i2.NetworkState>);

  @override
  _i4.Stream<bool> get hasInternetConnection => (super.noSuchMethod(
        Invocation.getter(#hasInternetConnection),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);

  @override
  _i4.Stream<_i2.NetworkMode> get currentMode => (super.noSuchMethod(
        Invocation.getter(#currentMode),
        returnValue: _i4.Stream<_i2.NetworkMode>.empty(),
      ) as _i4.Stream<_i2.NetworkMode>);

  @override
  _i2.NetworkState get currentNetworkState => (super.noSuchMethod(
        Invocation.getter(#currentNetworkState),
        returnValue: _FakeNetworkState_0(
          this,
          Invocation.getter(#currentNetworkState),
        ),
      ) as _i2.NetworkState);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isOffline => (super.noSuchMethod(
        Invocation.getter(#isOffline),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setMode(_i2.NetworkMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setMode,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> checkInternetConnection() => (super.noSuchMethod(
        Invocation.method(
          #checkInternetConnection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
