// Mocks generated by Mockito 5.4.4 from annotations
// in boofer/test/screens/chat_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:boofer/models/message_model.dart' as _i4;
import 'package:boofer/models/network_state.dart' as _i5;
import 'package:boofer/services/chat_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChatService extends _i1.Mock implements _i2.IChatService {
  MockIChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Message>> get messagesStream => (super.noSuchMethod(
        Invocation.getter(#messagesStream),
        returnValue: _i3.Stream<List<_i4.Message>>.empty(),
      ) as _i3.Stream<List<_i4.Message>>);

  @override
  _i3.Stream<_i5.NetworkState> get networkState => (super.noSuchMethod(
        Invocation.getter(#networkState),
        returnValue: _i3.Stream<_i5.NetworkState>.empty(),
      ) as _i3.Stream<_i5.NetworkState>);

  @override
  _i3.Stream<bool> get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  bool get isOnlineMode => (super.noSuchMethod(
        Invocation.getter(#isOnlineMode),
        returnValue: false,
      ) as bool);

  @override
  bool get isOfflineMode => (super.noSuchMethod(
        Invocation.getter(#isOfflineMode),
        returnValue: false,
      ) as bool);

  @override
  _i5.NetworkMode get currentMode => (super.noSuchMethod(
        Invocation.getter(#currentMode),
        returnValue: _i5.NetworkMode.online,
      ) as _i5.NetworkMode);

  @override
  _i3.Stream<int> get queueSize => (super.noSuchMethod(
        Invocation.getter(#queueSize),
        returnValue: _i3.Stream<int>.empty(),
      ) as _i3.Stream<int>);

  @override
  _i3.Stream<Map<String, int>> get queueStats => (super.noSuchMethod(
        Invocation.getter(#queueStats),
        returnValue: _i3.Stream<Map<String, int>>.empty(),
      ) as _i3.Stream<Map<String, int>>);

  @override
  _i3.Future<void> initialize({
    required String? supabaseUrl,
    required String? supabaseAnonKey,
    required String? bridgefyApiKey,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #supabaseUrl: supabaseUrl,
            #supabaseAnonKey: supabaseAnonKey,
            #bridgefyApiKey: bridgefyApiKey,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendMessage(
    String? text, {
    String? conversationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [text],
          {#conversationId: conversationId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> switchMode(_i5.NetworkMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #switchMode,
          [mode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> retryFailedMessages() => (super.noSuchMethod(
        Invocation.method(
          #retryFailedMessages,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  Map<String, dynamic> getServiceStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getServiceStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> processMessageQueue() => (super.noSuchMethod(
        Invocation.method(
          #processMessageQueue,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearMessageQueue() => (super.noSuchMethod(
        Invocation.method(
          #clearMessageQueue,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
