class AppConstants {
  static const String booferId = '00000000-0000-4000-8000-000000000000';
  static const String hytunesId = '11111111-1111-4111-a111-111111111111';
  static const String shaadowId = '22222222-2222-4222-a222-222222222222';
  static const String suryaId = '33333333-3333-4333-a333-333333333333';

  static const List<String> officialIds = [
    booferId,
    hytunesId,
    shaadowId,
    suryaId,
  ];

  static const List<(String, String)> interestOptions = [
    ('Music 🎵', 'Music'),
    ('Movies 🎬', 'Movies'),
    ('Travel ✈️', 'Travel'),
    ('Sports ⚽', 'Sports'),
    ('Gaming 🎮', 'Gaming'),
    ('Food 🍕', 'Food'),
    ('Art 🎨', 'Art'),
    ('Books 📚', 'Books'),
    ('Fitness 💪', 'Fitness'),
    ('Tech 💻', 'Tech'),
    ('Fashion 👗', 'Fashion'),
    ('Memes 😂', 'Memes'),
    ('Anime 🌸', 'Anime'),
    ('Nature 🌿', 'Nature'),
    ('Photography 📷', 'Photography'),
    ('Astrology 🔮', 'Astrology'),
    ('Comedy 😄', 'Comedy'),
    ('Podcasts 🎙️', 'Podcasts'),
  ];

  static const List<(String, String)> hobbyOptions = [
    ('Cooking 🍳', 'Cooking'),
    ('Dancing 💃', 'Dancing'),
    ('Drawing 🖌️', 'Drawing'),
    ('Hiking 🏔️', 'Hiking'),
    ('Yoga 🧘', 'Yoga'),
    ('Cycling 🚴', 'Cycling'),
    ('Reading 📖', 'Reading'),
    ('Singing 🎤', 'Singing'),
    ('DIY 🔨', 'DIY'),
    ('Meditation 🕯️', 'Meditation'),
    ('Vlogging 📹', 'Vlogging'),
    ('Writing ✍️', 'Writing'),
    ('Board Games 🎲', 'Board Games'),
    ('Surfing 🏄', 'Surfing'),
    ('Gardening 🌱', 'Gardening'),
    ('Skating ⛷️', 'Skating'),
  ];

  static const List<String> avatarOptions = [
    // Faces & People
    '👤',
    '😎',
    '🧙‍♂️',
    '🧛‍♀️',
    '🧑‍🚀',
    '🧑‍🎨',
    '🧑‍💻',
    '🎮',
    '🎭',
    '🥷',
    '🧖‍♂️',
    '🧘‍♀️',
    // Animals & Nature
    '🐱',
    '🐶',
    '🦊',
    '🦁',
    '🐯',
    '🐼',
    '🐨',
    '🐸',
    '🦄',
    '🐙',
    '🦖',
    '🐉',
    '🦋',
    '🦉',
    '🦜',
    '🦚',
    '🦦',
    '🦥',
    '🦔',
    '🌵',
    '🌻',
    '🌸',
    '🍀',
    '🐚',
    // Food & Drink
    '🍕',
    '🍔',
    '🍟',
    '🍦',
    '🍩',
    '🍪',
    '🍎',
    '🍒',
    '🍓',
    '🥑',
    '🍣',
    '🍱',
    '🍿',
    '☕',
    '🍹',
    // Activities & Hobbies
    '⚽',
    '🏀',
    '🎾',
    '🏸',
    '🛹',
    '🚴‍♂️',
    '🎸',
    '🎹',
    '🎬',
    '🏆',
    '🎨',
    '🧩',
    '🧵',
    '🧶',
    '📸',
    '📚',
    // Objects & Symbols
    '🚀',
    '🛸',
    '🛰️',
    '🪐',
    '⭐',
    '🔥',
    '💎',
    '🌈',
    '💡',
    '🧪',
    '🧬',
    '🧿',
    '🪬',
    '☯️',
    '👑',
    '💄',
    '🕶️',
    '🧳',
    '💼',
    '👔',
    '💍',
    '🎓',
    '🎰',
    '🪩',
    // Zodiac
    '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓',
  ];
}
