import '../models/friend_model.dart';
import '../models/user_model.dart';
import '../models/message_model.dart';

class ScreenshotMode {
  static bool isEnabled = false;

  static List<Friend> get dummyActiveChats => [
    Friend(
      id: 'dummy1',
      name: 'Sarah Wilson',
      handle: 'sarah_w',
      avatar: '👩‍💼',
      lastMessage: 'The new design looks amazing! 🚀',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 5)),
      unreadCount: 2,
      isOnline: true,
      isVerified: true,
      lastSenderId: 'dummy1',
      virtualNumber: '9876543210',
      lastMessageStatus: MessageStatus.read,
    ),
    Friend(
      id: 'dummy2',
      name: 'James Chen',
      handle: 'jchen_dev',
      avatar: '👨‍💻',
      lastMessage: 'Are we still on for the meeting?',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 2)),
      unreadCount: 0,
      isOnline: false,
      isVerified: false,
      lastSenderId: 'me',
      virtualNumber: '1234567890',
      lastMessageStatus: MessageStatus.delivered,
    ),
    Friend(
      id: 'dummy3',
      name: 'Elena Rodriguez',
      handle: 'elena_r',
      avatar: '🎨',
      lastMessage: 'Sent you the moodboard prototypes.',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 5)),
      unreadCount: 0,
      isOnline: true,
      isVerified: true,
      lastSenderId: 'dummy3',
      virtualNumber: '5550123456',
      lastMessageStatus: MessageStatus.read,
    ),
    Friend(
      id: 'dummy4',
      name: 'Chef Marco',
      handle: 'marco_kitchen',
      avatar: '👨‍🍳',
      lastMessage: 'The secret ingredient is out! 🍝',
      lastMessageTime: DateTime.now().subtract(const Duration(days: 1)),
      unreadCount: 0,
      isOnline: false,
      isVerified: false,
      lastSenderId: 'dummy4',
      virtualNumber: '4449998888',
      lastMessageStatus: MessageStatus.read,
    ),
    Friend(
      id: 'dummy5',
      name: 'Oliver Smith',
      handle: 'oliver_travels',
      avatar: '🌍',
      lastMessage: 'Check out these photos from Kyoto! ⛩️',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 45)),
      unreadCount: 1,
      isOnline: true,
      isVerified: false,
      lastSenderId: 'dummy5',
      virtualNumber: '7776665554',
      lastMessageStatus: MessageStatus.read,
    ),
    Friend(
      id: 'dummy6',
      name: 'Sophia Lee',
      handle: 'sophia_fit',
      avatar: '👟',
      lastMessage: 'Early morning workout done! 💪',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 3)),
      unreadCount: 0,
      isOnline: false,
      isVerified: true,
      lastSenderId: 'me',
      virtualNumber: '8887776665',
      lastMessageStatus: MessageStatus.read,
    ),
    Friend(
      id: 'dummy7',
      name: 'Dr. Watson',
      handle: 'watson_med',
      avatar: '👨‍⚕️',
      lastMessage: 'Your results came back all clear.',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 8)),
      unreadCount: 0,
      isOnline: true,
      isVerified: true,
      lastSenderId: 'dummy7',
      virtualNumber: '1112223334',
      lastMessageStatus: MessageStatus.read,
    ),
    Friend(
      id: 'dummy8',
      name: 'Zara Blue',
      handle: 'zara_fashion',
      avatar: '👗',
      lastMessage: 'Did you see the latest runway show?',
      lastMessageTime: DateTime.now().subtract(const Duration(days: 2)),
      unreadCount: 5,
      isOnline: false,
      isVerified: false,
      lastSenderId: 'dummy8',
      virtualNumber: '9990001112',
      lastMessageStatus: MessageStatus.read,
    ),
    Friend(
      id: 'dummy9',
      name: 'Liam Nova',
      handle: 'liam_space',
      avatar: '👨‍🚀',
      lastMessage: 'The moon looks incredible tonight. 🌕',
      lastMessageTime: DateTime.now().subtract(const Duration(minutes: 20)),
      unreadCount: 0,
      isOnline: true,
      isVerified: true,
      lastSenderId: 'me',
      virtualNumber: '4445556667',
      lastMessageStatus: MessageStatus.sent,
    ),
    Friend(
      id: 'dummy10',
      name: 'Mia Heart',
      handle: 'mia_vlogs',
      avatar: '🤳',
      lastMessage: 'New video is live! Go watch! ❤️',
      lastMessageTime: DateTime.now().subtract(const Duration(hours: 12)),
      unreadCount: 0,
      isOnline: false,
      isVerified: true,
      lastSenderId: 'dummy10',
      virtualNumber: '3334445556',
      lastMessageStatus: MessageStatus.read,
    ),
  ];

  static List<Friend> get dummyArchivedChats => [
    Friend(
      id: 'dummy_arch1',
      name: 'Old Project Group',
      handle: 'project_alpha',
      avatar: '📁',
      lastMessage: 'Group was archived.',
      lastMessageTime: DateTime.now().subtract(const Duration(days: 30)),
      unreadCount: 0,
      isOnline: false,
      virtualNumber: '0001112222',
    ),
    Friend(
      id: 'dummy_arch2',
      name: 'College Buddies',
      handle: 'class_of_22',
      avatar: '🎓',
      lastMessage: 'See you at the reunion!',
      lastMessageTime: DateTime.now().subtract(const Duration(days: 90)),
      unreadCount: 0,
      isOnline: false,
      virtualNumber: '9998887771',
    ),
  ];

  static List<User> get dummyDiscoverUsers => [];

  static User get dummyCurrentProfile => User(
    id: 'me',
    fullName: 'Alex Jordan',
    handle: 'alex_j',
    avatar: '🙋‍♂️',
    bio:
        'Coffee lover ☕ | Tech enthusiast | Exploring the world one city at a time. Let\'s connect!',
    age: 25,
    interests: ['Technology', 'Travel', 'Food', 'Movies', 'Music'],
    hobbies: ['Photography', 'Hiking', 'Cooking', 'Gaming', 'Reading'],
    followerCount: 1250,
    followingCount: 432,
    isVerified: true,
    email: 'alex@example.com',
    isDiscoverable: true,
    virtualNumber: '7778889990',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  );
}
