default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Google Play"
  lane :internal do
    # Upload to Google Play (Internal track)
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_screenshots: true,
      skip_upload_metadata: false
    )
  end

  desc "Promote Internal to Beta"
  lane :promote_to_beta do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'beta'
    )
  end
end
