// Mocks generated by Mockito 5.4.6 from annotations
// in boofer/test/e2e/app_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:boofer/models/message_model.dart' as _i6;
import 'package:boofer/models/network_state.dart' as _i2;
import 'package:boofer/services/backup/mesh_service.dart' as _i3;
import 'package:boofer/services/backup/network_service.dart' as _i7;
import 'package:boofer/services/backup/online_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNetworkState_0 extends _i1.SmartFake implements _i2.NetworkState {
  _FakeNetworkState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IMeshService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMeshService extends _i1.Mock implements _i3.IMeshService {
  MockIMeshService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<String> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  _i4.Stream<dynamic> get incomingMessages =>
      (super.noSuchMethod(
            Invocation.getter(#incomingMessages),
            returnValue: _i4.Stream<dynamic>.empty(),
          )
          as _i4.Stream<dynamic>);

  @override
  _i4.Stream<String> get deviceConnectionStream =>
      (super.noSuchMethod(
            Invocation.getter(#deviceConnectionStream),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isStarted =>
      (super.noSuchMethod(Invocation.getter(#isStarted), returnValue: false)
          as bool);

  @override
  bool get isActive =>
      (super.noSuchMethod(Invocation.getter(#isActive), returnValue: false)
          as bool);

  @override
  int get peersCount =>
      (super.noSuchMethod(Invocation.getter(#peersCount), returnValue: 0)
          as int);

  @override
  int get connectedPeersCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedPeersCount),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<void> initialize(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [apiKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendMessage(String? message, String? recipientId) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message, recipientId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendBroadcastMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendBroadcastMessage, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendMeshMessage(String? text, String? senderId) =>
      (super.noSuchMethod(
            Invocation.method(#sendMeshMessage, [text, senderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IOnlineService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOnlineService extends _i1.Mock implements _i5.IOnlineService {
  MockIOnlineService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.Message> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i4.Stream<_i6.Message>.empty(),
          )
          as _i4.Stream<_i6.Message>);

  @override
  _i4.Stream<dynamic> get incomingMessages =>
      (super.noSuchMethod(
            Invocation.getter(#incomingMessages),
            returnValue: _i4.Stream<dynamic>.empty(),
          )
          as _i4.Stream<dynamic>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize(String? supabaseUrl, String? supabaseKey) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [supabaseUrl, supabaseKey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendMessage(_i6.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendOnlineMessage(String? text, String? senderId) =>
      (super.noSuchMethod(
            Invocation.method(#sendOnlineMessage, [text, senderId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncOfflineMessages(List<_i6.Message>? messages) =>
      (super.noSuchMethod(
            Invocation.method(#syncOfflineMessages, [messages]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Message>> getRecentMessages({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentMessages, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i6.Message>>.value(<_i6.Message>[]),
          )
          as _i4.Future<List<_i6.Message>>);

  @override
  _i4.Future<List<_i6.Message>> getConversationMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessages, [conversationId]),
            returnValue: _i4.Future<List<_i6.Message>>.value(<_i6.Message>[]),
          )
          as _i4.Future<List<_i6.Message>>);

  @override
  void setCurrentUserId(String? userId) => super.noSuchMethod(
    Invocation.method(#setCurrentUserId, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getConnectionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [INetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkService extends _i1.Mock implements _i7.INetworkService {
  MockINetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.NetworkState> get networkState =>
      (super.noSuchMethod(
            Invocation.getter(#networkState),
            returnValue: _i4.Stream<_i2.NetworkState>.empty(),
          )
          as _i4.Stream<_i2.NetworkState>);

  @override
  _i4.Stream<bool> get hasInternetConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasInternetConnection),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Stream<_i2.NetworkMode> get currentMode =>
      (super.noSuchMethod(
            Invocation.getter(#currentMode),
            returnValue: _i4.Stream<_i2.NetworkMode>.empty(),
          )
          as _i4.Stream<_i2.NetworkMode>);

  @override
  _i2.NetworkState get currentNetworkState =>
      (super.noSuchMethod(
            Invocation.getter(#currentNetworkState),
            returnValue: _FakeNetworkState_0(
              this,
              Invocation.getter(#currentNetworkState),
            ),
          )
          as _i2.NetworkState);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setMode(_i2.NetworkMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setMode, [mode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> checkInternetConnection() =>
      (super.noSuchMethod(
            Invocation.method(#checkInternetConnection, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> refreshNetworkState() =>
      (super.noSuchMethod(
            Invocation.method(#refreshNetworkState, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, dynamic> getNetworkStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getNetworkStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
